package generators_test

import (
	"splash/internal/generators"
	"splash/internal/models"
	"testing"
)

func TestAlacritty(t *testing.T) {
	palette, _ := models.PaletteFromJson([]byte(JSON))
	gen := &generators.AlacrittyGenerator{}
	result := gen.Generate(palette)
	expected := `# Generated by splash
[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

[colors.normal]
black   = '#181818'
red     = '#ab4642'
green   = '#a16946'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

[colors.bright]
black   = '#585858'
red     = '#ab4642'
green   = '#a16946'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'
`
	if string(result) != expected {
		t.Errorf("alacritty generator does not generate the correct output")
	}
}
