package generators

import (
	"fmt"
	"splash/internal/models"
)

type AlacrittyGenerator struct{}

func (g *AlacrittyGenerator) Generate(palette *models.Base16Palette) []byte {
	p := *palette
	output := fmt.Sprintf(`# Generated by splash
[colors.primary]
background = '%s'
foreground = '%s'

[colors.cursor]
text = '%s'
cursor = '%s'

[colors.normal]
black   = '%s'
red     = '%s'
green   = '%s'
yellow  = '%s'
blue    = '%s'
magenta = '%s'
cyan    = '%s'
white   = '%s'

[colors.bright]
black   = '%s'
red     = '%s'
green   = '%s'
yellow  = '%s'
blue    = '%s'
magenta = '%s'
cyan    = '%s'
white   = '%s'
`,
		p.B00.ToHex(), // bg
		p.B05.ToHex(), // fg
		p.B00.ToHex(), // cursor-text
		p.B05.ToHex(), // cursor-bg
		// normal
		p.B00.ToHex(), // black
		p.B08.ToHex(), // red
		p.B0f.ToHex(), // green
		p.B0a.ToHex(), // yellow
		p.B0d.ToHex(), // blue
		p.B0e.ToHex(), // magenta
		p.B0c.ToHex(), // cyan
		p.B05.ToHex(), // white
		// bright
		p.B03.ToHex(), // black
		p.B08.ToHex(), // red
		p.B0f.ToHex(), // green
		p.B0a.ToHex(), // yellow
		p.B0d.ToHex(), // blue
		p.B0e.ToHex(), // magenta
		p.B0c.ToHex(), // cyan
		p.B05.ToHex(), // white
	)

	return []byte(output)
}
