package generators

import (
	"fmt"
	"splash/internal/models"
)

type GhosttyGenerator struct{}

func (g *GhosttyGenerator) Generate(palette *models.Base16Palette) []byte {
	p := *palette
	output := fmt.Sprintf(`# Generated by splash
palette = 0=%s
palette = 1=%s
palette = 2=%s
palette = 3=%s
palette = 4=%s
palette = 5=%s
palette = 6=%s
palette = 7=%s
palette = 8=%s
palette = 9=%s
palette = 10=%s
palette = 11=%s
palette = 12=%s
palette = 13=%s
palette = 14=%s
palette = 15=%s
background = %s
foreground = %s
cursor-color = %s
cursor-text = %s
selection-background = %s
selection-foreground = %s
`,
		p.B00.ToHex(),
		p.B01.ToHex(),
		p.B02.ToHex(),
		p.B03.ToHex(),
		p.B04.ToHex(),
		p.B05.ToHex(),
		p.B06.ToHex(),
		p.B07.ToHex(),
		p.B08.ToHex(),
		p.B09.ToHex(),
		p.B0a.ToHex(),
		p.B0b.ToHex(),
		p.B0c.ToHex(),
		p.B0d.ToHex(),
		p.B0e.ToHex(),
		p.B0f.ToHex(),
		p.B00.ToHex(), // background
		p.B05.ToHex(), // foreground
		p.B05.ToHex(), // cursor-color
		p.B00.ToHex(), // cursor-text
		p.B02.ToHex(), // selection-background
		p.B00.ToHex(), // selection-foreground
	)

	return []byte(output)
}
