package generators_test

import (
	"splash/internal/generators"
	"splash/internal/models"
	"testing"
)

func TestGhostty(t *testing.T) {
	palette, _ := models.PaletteFromJson([]byte(JSON))
	gen := &generators.GhosttyGenerator{}
	result := gen.Generate(palette)
	expected := `# Generated by splash
palette = 0=#181818
palette = 1=#282828
palette = 2=#383838
palette = 3=#585858
palette = 4=#b8b8b8
palette = 5=#d8d8d8
palette = 6=#e8e8e8
palette = 7=#f8f8f8
palette = 8=#ab4642
palette = 9=#dc9656
palette = 10=#f7ca88
palette = 11=#a1b56c
palette = 12=#86c1b9
palette = 13=#7cafc2
palette = 14=#ba8baf
palette = 15=#a16946
background = #181818
foreground = #d8d8d8
cursor-color = #d8d8d8
cursor-text = #181818
selection-background = #383838
selection-foreground = #181818
`
	if string(result) != expected {
		t.Errorf("ghostty generator does not generate the correct output")
	}
}
