package generators_test

import (
	"splash/internal/generators"
	"splash/internal/models"
	"testing"
)

func TestKitty(t *testing.T) {
	palette, _ := models.PaletteFromJson([]byte(JSON))
	gen := &generators.KittyGenerator{}
	result := gen.Generate(palette)
	expected := `# Generated by splash
background #181818
foreground #d8d8d8
cursor #d8d8d8
selection_background #383838
selection_foreground #181818
color0 #181818
color1 #282828
color2 #383838
color3 #585858
color4 #b8b8b8
color5 #d8d8d8
color6 #e8e8e8
color7 #f8f8f8
color8 #ab4642
color9 #dc9656
color10 #f7ca88
color11 #a1b56c
color12 #86c1b9
color13 #7cafc2
color14 #ba8baf
color15 #a16946
`

	if string(result) != expected {
		t.Errorf("kitty generator does not generate the correct output")
	}
}
