package generators

import (
	"fmt"
	"splash/internal/models"
)

type NvimGenerator struct{}

func (g *NvimGenerator) Generate(palette *models.Base16Palette) []byte {
	p := *palette
	output := fmt.Sprintf(`-- Generated by splash
require('base16-colorscheme').setup({
    base00 = '%s', base01 = '%s', base02 = '%s', base03 = '%s',
    base04 = '%s', base05 = '%s', base06 = '%s', base07 = '%s',
    base08 = '%s', base09 = '%s', base0A = '%s', base0B = '%s',
    base0C = '%s', base0D = '%s', base0E = '%s', base0F = '%s',
})`,
		p.B00.ToHex(),
		p.B01.ToHex(),
		p.B02.ToHex(),
		p.B03.ToHex(),
		p.B04.ToHex(),
		p.B05.ToHex(),
		p.B06.ToHex(),
		p.B07.ToHex(),
		p.B08.ToHex(),
		p.B09.ToHex(),
		p.B0a.ToHex(),
		p.B0b.ToHex(),
		p.B0c.ToHex(),
		p.B0d.ToHex(),
		p.B0e.ToHex(),
		p.B0f.ToHex(),
	)

	return []byte(output)
}
