package generators

import (
	"fmt"
	"splash/internal/models"
)

type NvimGenerator struct{}

func (g *NvimGenerator) Generate(palette *models.Base16Palette) []byte {
	p := *palette
	output := fmt.Sprintf(`-- Generated by splash
require('base16-colorscheme').setup({
    base00 = '%s', base01 = '%s', base02 = '%s', base03 = '%s',
    base04 = '%s', base05 = '%s', base06 = '%s', base07 = '%s',
    base08 = '%s', base09 = '%s', base0A = '%s', base0B = '%s',
    base0C = '%s', base0D = '%s', base0E = '%s', base0F = '%s',
})
    `,
		p.B00.HexStringFromColor(),
		p.B01.HexStringFromColor(),
		p.B02.HexStringFromColor(),
		p.B03.HexStringFromColor(),
		p.B04.HexStringFromColor(),
		p.B05.HexStringFromColor(),
		p.B06.HexStringFromColor(),
		p.B07.HexStringFromColor(),
		p.B08.HexStringFromColor(),
		p.B09.HexStringFromColor(),
		p.B0a.HexStringFromColor(),
		p.B0b.HexStringFromColor(),
		p.B0c.HexStringFromColor(),
		p.B0d.HexStringFromColor(),
		p.B0e.HexStringFromColor(),
		p.B0f.HexStringFromColor(),
	)

	return []byte(output)
}
