package generators

import (
	"fmt"
	"splash/internal/models"
)

type NvimGenerator struct{}

func (g *NvimGenerator) Generate(palette *models.Base16Palette) []byte {
	p := *palette
	output := fmt.Sprintf(`-- Generated by splash
require('base16-colorscheme').setup({
    base00 = '%s', base01 = '%s', base02 = '%s', base03 = '%s',
    base04 = '%s', base05 = '%s', base06 = '%s', base07 = '%s',
    base08 = '%s', base09 = '%s', base0A = '%s', base0B = '%s',
    base0C = '%s', base0D = '%s', base0E = '%s', base0F = '%s',
})`,
		p.B00.ToHexString(),
		p.B01.ToHexString(),
		p.B02.ToHexString(),
		p.B03.ToHexString(),
		p.B04.ToHexString(),
		p.B05.ToHexString(),
		p.B06.ToHexString(),
		p.B07.ToHexString(),
		p.B08.ToHexString(),
		p.B09.ToHexString(),
		p.B0a.ToHexString(),
		p.B0b.ToHexString(),
		p.B0c.ToHexString(),
		p.B0d.ToHexString(),
		p.B0e.ToHexString(),
		p.B0f.ToHexString(),
	)

	return []byte(output)
}
