package generators

import (
	"fmt"
	"splash/internal/models"
)

type WeztermGenerator struct{}

func (g *WeztermGenerator) Generate(palette *models.Base16Palette) []byte {
	p := *palette
	output := fmt.Sprintf(`# Generated by splash
# Usage:    place this file in ~/.config/wezterm/colors/
#           in your config: config.color_scheme = "splash"
[metadata]
name = "splash"

[colors]
ansi = [
    "%s",
    "%s",
    "%s",
    "%s",
    "%s",
    "%s",
    "%s",
    "%s",
]
background = "%s"
brights = [
    "%s",
    "%s",
    "%s",
    "%s",
    "%s",
    "%s",
    "%s",
    "%s",
]
cursor_bg = "%s"
cursor_border = "%s"
cursor_fg = "%s"
foreground = "%s"
selection_bg = "%s"
selection_fg = "%s"
`,
		p.B00.ToHex(),
		p.B01.ToHex(),
		p.B02.ToHex(),
		p.B03.ToHex(),
		p.B04.ToHex(),
		p.B05.ToHex(),
		p.B06.ToHex(),
		p.B07.ToHex(),
		p.B00.ToHex(),
		p.B08.ToHex(),
		p.B09.ToHex(),
		p.B0a.ToHex(),
		p.B0b.ToHex(),
		p.B0c.ToHex(),
		p.B0d.ToHex(),
		p.B0e.ToHex(),
		p.B0f.ToHex(),
		p.B07.ToHex(),
		p.B07.ToHex(),
		p.B00.ToHex(),
		p.B07.ToHex(),
		p.B07.ToHex(),
		p.B00.ToHex())
	return []byte(output)
}
