package generators_test

import (
	"reflect"
	"splash/internal/generators"
	"splash/internal/models"
	"testing"
)

func TestWezterm(t *testing.T) {
	palette, _ := models.PaletteFromJson([]byte(JSON))
	gen := &generators.WeztermGenerator{}
	result := gen.Generate(palette)
	expected := `# Generated by splash
# Generated by splash
# Usage:    place this file in ~/.config/wezterm/colors/
#           in your config: config.color_scheme = "splash"
[metadata]
name = "splash"

[colors]
ansi = [
    "#181818",
    "#282828",
    "#383838",
    "#585858",
    "#b8b8b8",
    "#d8d8d8",
    "#e8e8e8",
    "#f8f8f8",
]
background = "#181818"
brights = [
    "#ab4642",
    "#dc9656",
    "#f7ca88",
    "#a1b56c",
    "#86c1b9",
    "#7cafc2",
    "#ba8baf",
    "#a16946",
]
cursor_bg = "#f8f8f8"
cursor_border = "#f8f8f8"
cursor_fg = "#181818"
foreground = "#f8f8f8"
selection_bg = "#f8f8f8"
selection_fg = "#181818"`
	if reflect.DeepEqual(string(result), expected) {
		t.Errorf("wezterm generator does not generate the correct output")
	}
}
